# Generated by Django 6.0.6 on 2026-06-13 19:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('target_skill', models.CharField(db_index=True, max_length=100)),
                ('target_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='roadmaps.roadmap')),
            ],
            options={
                'db_table': 'phases',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='roadmaps.phase')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['user', 'status'], name='roadmaps_user_id_1549e8_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['user', 'target_skill', 'target_level'], name='roadmaps_user_id_831cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['-created_at'], name='roadmaps_created_f31040_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roadmap',
            unique_together={('user', 'target_skill', 'target_level', 'status')},
        ),
        migrations.AddIndex(
            model_name='phase',
            index=models.Index(fields=['roadmap', 'order'], name='phases_roadmap_848758_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('roadmap', 'order')},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['phase', 'is_completed'], name='topics_phase_i_81bc52_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_completed', '-completed_at'], name='topics_is_comp_f4e627_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('phase', 'order')},
        ),
    ]
